import { Order } from '@prisma/client';

export class orderMappers {
  static mapToInsert(input: any): any {
    return {
      id: input.OrderID ? Number(input.OrderID) : 1,
      orderDate: input.OrderDate,
      invoiceableOn: input.InvoiceableOn,
      affiliateCommissionableValue: input.AffiliateCommissionableValue,

      orderStatus: input.OrderStatus || undefined,
      userId: input.UserId,
      // modifiedBy: { connect: { id: input.LastModBy } },
      trackingNo: input.TrackingNo,
      shippingMethodId: input.ShippingMethodId,
      totalShippingCost: input.TotalShippingCost,
      // customer: { connect: { id: input.CustomerId } },
      // salesRep: { connect: { id: input.SalesRepCustomerId } },
      // endUser: { connect: { id: input.EndUserId } },
      billingFirstName: input.BillingFirstName || undefined,
      billingLastName: input.BillingLastName || undefined,
      billingCompanyName: input.BillingCompanyName || undefined,
      billingAddress1: input.BillingAddress1 || undefined,
      billingAddress2: input.BillingAddress2 || undefined,
      billingCity: input.BillingCity || undefined,
      billingState: input.BillingState || undefined,
      billingPostalCode: input.BillingPostalCode || undefined,
      billingCountry: input.BillingCountry || undefined,
      billingPhoneNumber: input.BillingPhoneNumber || undefined,
      shipFirstName: input.ShipFirstName || undefined,
      shipLastName: input.ShipLastName || undefined,
      shipCompanyName: input.ShipCompanyName || undefined,
      shipAddress1: input.ShipAddress1 || undefined,
      shipAddress2: input.ShipAddress2 || undefined,
      shipCity: input.ShipCity || undefined,
      shipState: input.ShipState || undefined,
      shipPostalCode: input.ShipPostalCode || undefined,
      shipCountry: input.ShipCountry || undefined,
      shipPhoneNumber: input.ShipPhoneNumber || undefined,
      shipEmailAddress: input.ShipEmailAddress || undefined,
      orderComments: input.OrderComments || undefined,
      orderNotes: input.OrderNotes || undefined,
      poNum: input.poNum || undefined,
      paymentAmount: input.PaymentAmount,
      paymentMethodId: input.PaymentMethodId,
      salesTaxRate1: input.SalesTaxRate1,
      salesTax1: input.SalesTax1,
      salesTaxRate2: input.SalesTaxRate2,
      salesTax2: input.SalesTax2,
      salesTaxRate3: input.SalesTaxRate3,
      salesTax3: input.SalesTax3,
      isPayed: input.IsPayed,
      isTaxExempt: Boolean(input.IsTaxExempt),
      orderType: input.OrderType || undefined,
      orderSerials: input.OrderSerials || undefined,
      isAGift: input.IsAGift || undefined,
      insuranceValue: input.InsuranceValue,
      incoterm: input.Incoterm,
      taxExemptionId: input.TaxExemptionId,
      totalPaymentReceived: input.TotalPaymentReceived,
      currentCustomerDiscount: input.CurrentCustomerDiscount,
      isCustomerNameShow: input.IsCustomerNameShow !== undefined,
      isCustomerEmailShow: input.IsCustomerEmailShow !== undefined,
      isGTSOrder: input.IsGTSOrder === 'false' ? 'N' : 'Y',
      shipResidential: input.ShipResidential,
      shipped: input.Shipped.toString(),
      stockPriority: input.StockPriority,
      tax1Title: input.Tax1Title,
      totalPaymentAuthorized: input.TotalPaymentAuthorized,
    };
  }

  static mapOrderDetailToInsert(input: any): any {
    return {
      orderId: Number(input.OrderID),
      // productId: Number(input.productId),
      productCode: input.productCode,
      description: input.description,
      qtyOnPackingSlip: Number(input.qtyOnPackingSlip),
      isChild: Boolean(input.isChild),
      displayOrder: Number(input.displayOrder),
      productName: input.productName,
      productWeight: Number(input.productWeight),
      quantity: Number(input.quantity),
      taxableProduct: String(input.taxableProduct),
      qtyShipped: Number(input.qtyShipped),
      qtyOnBackOrder: Number(input.qtyOnBackOrder),
    };
  }

  static mapOrdersByStatus(order, totalCount, tagName, paymentAmountSum): any {
    return {
      ProductCode: order.orderDetails
        .map((detail) => detail.productCode)
        .join(','),
      IsPayed: order.isPayed,
      OrderNotes: order.orderNotes,
      BillingAddress1: order.billingAddress1,
      BillingAddress2: order.billingAddress2,
      PONum: order.poNum,
      BillingCity: order.billingCity,
      BillingCompanyName: order.billingCompanyName,
      BillingCountry: order.billingCountry,
      BillingFaxNumber: order.billingFaxNumber,
      BillingFirstName: order.billingFirstName,
      BillingLastName: order.billingLastName,
      BillingPhoneNumber: order.billingPhoneNumber,
      BillingPostalCode: order.billingPostalCode,
      BillingState: order.billingState,
      Order_Comments: order.orderComments,
      ShipAddress1: order.shipAddress1,
      ShipAddress2: order.shipAddress2,
      ShipCity: order.shipCity,
      ShipCompanyName: order.shipCompanyName,
      ShipCountry: order.shipCountry,
      ShipDate: order.shipDate,
      CancelDate: order.cancelDate,
      ShipFaxNumber: order.shipFaxNumber,
      ShipFirstName: order.shipFirstName,
      ShipLastName: order.shipLastName,
      Shipped: order.shipped,
      ShipPhoneNumber: order.shipPhoneNumber,
      ShipPostalCode: order.shipPostalCode,
      ShipState: order.shipState,
      Order_Entry_System: order.orderEntrySystem,
      OrderSerials: order.orderSerials,
      OldOrder: order.oldOrder,
      OrderID: order.id,
      QuoteNo: order.quoteNo,
      QuoteDate: order.quote?.quoteDate,
      InvoiceableOn: order.invoiceableOn,
      CustomerID: order.customerId,
      OrderStatus: order.orderStatus,
      PaymentAmount: order.paymentAmount,
      CompanyName: order.billingCompanyName,
      FirstName: order.billingFirstName,
      LastName: order.billingLastName,
      OrderDate: order.orderDate,
      City: order.billingCity,
      EmailAddress: order.customer?.email,
      CreatedByBlueFirstName: order.orderedBy?.firstname,
      CreatedByBlueLastName: order.orderedBy?.lastname,
      CreatedByVoluFirstName: order.salesRep?.firstName,
      CreatedByVoluLastName: order.salesRep?.lastName,
      tagName,
      totalAmount: paymentAmountSum.toFixed(2),
      count: totalCount,
    };
  }

  static mapOrdersByOpenStatus(order): any {
    return {
      ProductCode: order.orderDetails
        .map((detail) => detail.productCode)
        .join(','), // Combine multiple ProductCodes
      IsPayed: order.isPayed,
      OrderNotes: order.orderNotes,
      BillingAddress1: order.billingAddress1,
      BillingAddress2: order.billingAddress2,
      PONum: order.poNum,
      BillingCity: order.billingCity,
      BillingCompanyName: order.billingCompanyName,
      BillingCountry: order.billingCountry,
      BillingFaxNumber: order.billingFaxNumber,
      BillingFirstName: order.billingFirstName,
      BillingLastName: order.billingLastName,
      BillingPhoneNumber: order.billingPhoneNumber,
      BillingPostalCode: order.billingPostalCode,
      BillingState: order.billingState,
      Order_Comments: order.orderComments,
      ShipAddress1: order.shipAddress1,
      ShipAddress2: order.shipAddress2,
      ShipCity: order.shipCity,
      ShipCompanyName: order.shipCompanyName,
      ShipCountry: order.shipCountry,
      ShipDate: order.shipDate,
      CancelDate: order.cancelDate,
      ShipFaxNumber: order.shipFaxNumber,
      ShipFirstName: order.shipFirstName,
      ShipLastName: order.shipLastName,
      Shipped: order.shipped,
      ShipPhoneNumber: order.shipPhoneNumber,
      ShipPostalCode: order.shipPostalCode,
      ShipState: order.shipState,
      Order_Entry_System: order.orderEntrySystem,
      OrderSerials: order.orderSerials,
      OldOrder: order.oldOrder,
      OrderID: order.id,
      QuoteNo: order.quoteNo,
      QuoteDate: order.quote?.quoteDate,
      InvoiceableOn: order.invoiceableOn,
      CustomerID: order.customerId,
      OrderStatus: order.orderStatus,
      PaymentAmount: order.paymentAmount,
      CompanyName: order.billingCompanyName,
      FirstName: order.billingFirstName,
      LastName: order.billingLastName,
      OrderDate: order.orderDate,
      City: order.billingCity,
      EmailAddress: order.customer?.email,
      CreatedByBlueFirstName: order.orderedBy?.firstname,
      CreatedByBlueLastName: order.orderedBy?.lastname,
      CreatedByVoluFirstName: order.salesRep?.firstName,
      CreatedByVoluLastName: order.salesRep?.lastName,
    };
  }

  static mapGetOrders(order): any {
    return {
      IsPayed: order.isPayed,
      OrderNotes: order.orderNotes,
      BillingAddress1: order.billingAddress1,
      BillingAddress2: order.billingAddress2,
      PONum: order.poNum,
      orderDetails: order.orderDetails,
      BillingCity: order.billingCity,
      BillingCompanyName: order.billingCompanyName,
      BillingCountry: order.billingCountry,
      BillingFaxNumber: order.billingFaxNumber,
      BillingFirstName: order.billingFirstName,
      BillingLastName: order.billingLastName,
      BillingPhoneNumber: order.billingPhoneNumber,
      BillingPostalCode: order.billingPostalCode,
      BillingState: order.billingState,
      Order_Comments: order.orderComments,
      ShipAddress1: order.shipAddress1,
      ShipAddress2: order.shipAddress2,
      ShipCity: order.shipCity,
      ShipCompanyName: order.shipCompanyName,
      ShipCountry: order.shipCountry,
      ShipDate: order.shipDate,
      CancelDate: order.cancelDate,
      ShipFaxNumber: order.shipFaxNumber,
      ShipFirstName: order.shipFirstName,
      ShipLastName: order.shipLastName,
      Shipped: order.shipped,
      ShipPhoneNumber: order.shipPhoneNumber,
      ShipPostalCode: order.shipPostalCode,
      ShipState: order.shipState,
      Order_Entry_System: order.orderEntrySystem,
      OrderSerials: order.orderSerials,
      OldOrder: order.oldOrder,
      OrderID: order.id,
      QuoteNo: order.quoteNo,
      QuoteDate: order.quote?.quoteDate,
      InvoiceableOn: order.invoiceableOn,
      CustomerID: order.customerId,
      OrderStatus: order.orderStatus,
      PaymentAmount: order.paymentAmount,
      CompanyName: order.billingCompanyName,
      FirstName: order.billingFirstName,
      LastName: order.billingLastName,
      OrderDate: order.orderDate,
      City: order.billingCity,
      EmailAddress: order.customer?.email,
      CreatedByBlueFirstName: order.orderedBy?.firstname,
      CreatedByBlueLastName: order.orderedBy?.lastname,
      CreatedByVoluFirstName: order.salesRep?.firstName,
      CreatedByVoluLastName: order.salesRep?.lastName,
    };
  }

  static mapGetOrdersCSV(order: any): any {
    return {
      ProductCode: order.orderDetails
        .map((detail) => detail.productCode)
        .join(','),
      IsPayed: order.isPayed,
      OrderNotes: order.orderNotes,
      BillingAddress1: order.billingAddress1,
      BillingAddress2: order.billingAddress2,
      PONum: order.poNum,
      BillingCity: order.billingCity,
      BillingCompanyName: order.billingCompanyName,
      BillingCountry: order.billingCountry,
      BillingFaxNumber: order.billingFaxNumber,
      BillingFirstName: order.billingFirstName,
      BillingLastName: order.billingLastName,
      BillingPhoneNumber: order.billingPhoneNumber,
      BillingPostalCode: order.billingPostalCode,
      BillingState: order.billingState,
      Order_Comments: order.orderComments,
      ShipAddress1: order.shipAddress1,
      ShipAddress2: order.shipAddress2,
      ShipCity: order.shipCity,
      ShipCompanyName: order.shipCompanyName,
      ShipCountry: order.shipCountry,
      ShipDate: order.shipDate,
      CancelDate: order.cancelDate,
      ShipFaxNumber: order.shipFaxNumber,
      ShipFirstName: order.shipFirstName,
      ShipLastName: order.shipLastName,
      Shipped: order.shipped,
      ShipPhoneNumber: order.shipPhoneNumber,
      ShipPostalCode: order.shipPostalCode,
      ShipState: order.shipState,
      Order_Entry_System: order.orderEntrySystem,
      OrderSerials: order.orderSerials,
      OldOrder: order.oldOrder,
      OrderID: order.id,
      QuoteNo: order.quoteNo,
      QuoteDate: order.quote?.quoteDate,
      InvoiceableOn: order.invoiceableOn,
      CustomerID: order.customerId,
      OrderStatus: order.orderStatus,
      PaymentAmount: order.paymentAmount,
      CompanyName: order.billingCompanyName,
      FirstName: order.billingFirstName,
      LastName: order.billingLastName,
      OrderDate: order.orderDate,
      City: order.billingCity,
      EmailAddress: order.customer?.email,
      CreatedByBlueFirstName: order.orderedBy?.firstname,
      CreatedByBlueLastName: order.orderedBy?.lastname,
      CreatedByVoluFirstName: order.salesRep?.firstName,
      CreatedByVoluLastName: order.salesRep?.lastName,
      tagName: order.tagTable
        .map((tt) => {
          let name = tt.tag?.title || '';
          const changeText = name.indexOf('-');
          if (changeText !== -1) {
            name = name.substring(changeText + 1).trim();
          }
          return name;
        })
        .join(','),
    };
  }

  static mapGetOrdersProductsCSV(order): any {
    return {
      ProductCode: order.orderDetails
        .map((detail) => detail.productCode)
        .join(','),
      ProductID: order.orderDetails.map((detail) => detail.productId).join(','),
      IsPayed: order.isPayed,
      OrderNotes: order.orderNotes,
      BillingAddress1: order.billingAddress1,
      BillingAddress2: order.billingAddress2,
      PONum: order.poNum,
      BillingCity: order.billingCity,
      BillingCompanyName: order.billingCompanyName,
      BillingCountry: order.billingCountry,
      BillingFaxNumber: order.billingFaxNumber,
      BillingFirstName: order.billingFirstName,
      BillingLastName: order.billingLastName,
      BillingPhoneNumber: order.billingPhoneNumber,
      BillingPostalCode: order.billingPostalCode,
      BillingState: order.billingState,
      Order_Comments: order.orderComments,
      ShipAddress1: order.shipAddress1,
      ShipAddress2: order.shipAddress2,
      ShipCity: order.shipCity,
      ShipCompanyName: order.shipCompanyName,
      ShipCountry: order.shipCountry,
      ShipDate: order.shipDate,
      CancelDate: order.cancelDate,
      ShipFaxNumber: order.shipFaxNumber,
      ShipFirstName: order.shipFirstName,
      ShipLastName: order.shipLastName,
      Shipped: order.shipped,
      ShipPhoneNumber: order.shipPhoneNumber,
      ShipPostalCode: order.shipPostalCode,
      ShipState: order.shipState,
      Order_Entry_System: order.orderEntrySystem,
      OrderSerials: order.orderSerials,
      OldOrder: order.oldOrder,
      OrderID: order.id,
      QuoteNo: order.quoteNo,
      QuoteDate: order.quote?.quoteDate,
      InvoiceableOn: order.invoiceableOn,
      CustomerID: order.customerId,
      OrderStatus: order.orderStatus,
      PaymentAmount: order.paymentAmount,
      CompanyName: order.billingCompanyName,
      FirstName: order.billingFirstName,
      LastName: order.billingLastName,
      OrderDate: order.orderDate,
      City: order.billingCity,
      EmailAddress: order.customer?.email,
      CreatedByBlueFirstName: order.orderedBy?.firstname,
      CreatedByBlueLastName: order.orderedBy?.lastname,
      CreatedByVoluFirstName: order.salesRep?.firstName,
      CreatedByVoluLastName: order.salesRep?.lastName,
      tagName: order.tagTable
        .map((tt) => {
          let name = tt.tag?.title || '';
          const changeText = name.indexOf('-');
          if (changeText !== -1) {
            name = name.substring(changeText + 1).trim();
          }
          return name;
        })
        .join(','),
    };
  }
  static mapOrderDetails(detail): any {
    return {
      OptionID: detail.optionId,
      productId: detail.productId,
      categoryIdOfOption: detail.categoryIdOfOption,
      Options: detail.options,
      ProductSubClass: detail.productSubClass,
      TaxableProduct: detail.taxableProduct,
      QtyOnPackingSlip: detail.qtyOnPackingSlip,
      QtyShipped: detail.qtyShipped,
      QtyOnBackOrder: detail.qtyOnBackOrder,
      shippedQty: 0, // Computed below
      parent: detail.parent,
      parentName: detail.parentName,
      ProductSerials: detail.productSerials,
      isChild: detail.isChild,
      isCategoriesOption: detail.isCategoriesOption,
      ProductCode: detail.productCode,
      ProductName: detail.productName,
      description: detail.description,
      HarmonizedCode: detail.harmonizedCode,
      ExportControlClassificationNumber:
        detail.exportControlClassificationNumber,
      ProductWeight: detail.productWeight,
      UnitOfMeasure: detail.unitOfMeasure,
      CountryOfOrigin: detail.countryOfOrigin,
      ExportDescription: detail.exportDescription,
      Qty: detail.quantity,
      Price: detail.productPrice,
      Discount: detail.discountValue,
      gpn: detail.product?.gpn,
    };
  }

  static mapGetOrder(order, notes, orderDetails): any {
    return {
      OrderEntrySystem: order.orderEntrySystem || '',
      ShipEmailAddress: order.shipEmailAddress || '',
      InsuranceValue: order.insuranceValue,
      endUserId: order.endUserId,
      PONum: order.poNum || '',
      TrackingNo: order.trackingNo || '',
      Incoterm: order.incoterm || '',
      CreditCardAuthorizationHash: order.creditCardAuthorizationHash || '',
      CustomFieldCarrierAcctNo: order.customFieldCarrierAcctNo || '',
      IsPayed: order.isPayed || false,
      LastModBy: order.lastModBy,
      LastModified: order.lastModified
        ? new Date(order.lastModified)
        : undefined,
      OrderTaxExempt: order.orderTaxExempt || false,
      UserId: order.orderedBy?.id,
      TotalPaymentReceived: order.totalPaymentReceived,
      CurrentCustomerDiscount: order.currentCustomerDiscount,
      IsCustomerNameShow: order.isCustomerNameShow || false,
      OrderID: order.id,
      QuoteNo: order.quote?.quoteNo,
      OrderComments: order.orderComments || '',
      notes: order.orderComments || '',
      OrderNotes: order.orderNotes || '',
      //   PrivateNotes: order.privateNotes || '',
      PaymentAmount: order.paymentAmount || 0,
      CustomerCompany: order.billingCompanyName || '',
      ShipCompanyName: order.shipCompanyName || '',
      ShipFirstName: order.shipFirstName || '',
      ShipLastName: order.shipLastName || '',
      CustomerFName: order.billingFirstName || '',
      CustomerLName: order.billingLastName || '',
      OrderDate: order.orderDate ? new Date(order.orderDate) : undefined,
      OrderDatePDF: order.orderDate
        ? new Date(order.orderDate).toISOString().split('T')[0]
        : '',
      BillingStreetAddress1: order.billingAddress1 || '',
      BillingStreetAddress2: order.billingAddress2 || '',
      BillingCity1: order.billingCity || '',
      BillingCountry1: order.billingCountry || '',
      BillingState: order.billingState || '',
      BillingPhoneNumber: order.billingPhoneNumber || '',
      IsTaxExempt: order.orderTaxExempt || false,
      BillingPostalCode: order.billingPostalCode || '',
      ShipAddress1: order.shipAddress1 || '',
      ShipAddress2: order.shipAddress2 || '',
      ShipCity: order.shipCity || '',
      ShipCountry: order.shipCountry || '',
      ShipState: order.shipState || '',
      ShipPhoneNumber: order.shipPhoneNumber || '',
      ShipPostalCode: order.shipPostalCode || '',
      SalesTaxRate1:
        (order.salesTaxRate1 || 0) +
        (order.salesTaxRate2 || 0) +
        (order.salesTaxRate3 || 0),
      SalesTax1: order.salesTax1,
      IsCustomerEmailShow: order.isCustomerEmailShow || false,
      ModifiedByBlueFirstName: order.modifiedBy?.firstname || '',
      ModifiedByBlueLastName: order.modifiedBy?.lastname || '',
      CreatedByBlueFirstName: order.orderedBy?.firstname || '',
      CreatedByBlueLastName: order.orderedBy?.lastname || '',
      CreatedByVoluFirstName: order.salesRep?.firstName || '',
      CreatedByVoluLastName: order.salesRep?.lastName || '',
      OrderSerials: order.orderSerials || '',
      invoiceableOn: order.invoiceableOn
        ? new Date(order.invoiceableOn)
        : undefined,
      OrderStatus: order.orderStatus || '',
      OrderType: order.orderType || '',
      ShippingMethodID: order.shippingMethodId,
      Freight: order.totalShippingCost,
      OldOrder: order.oldOrder || false,
      TaxShipping:
        (order.salesTaxRate1 || 0) +
        (order.salesTaxRate2 || 0) +
        (order.salesTaxRate3 || 0),
      TotalTax:
        (order.salesTax1 || 0) +
        (order.salesTax2 || 0) +
        (order.salesTax3 || 0),
      CustomerID: order.customerId,
      tagIds: order.tagTable?.map((tt) => tt.tagId) || [],
      notesHistory: notes,
      orderDetails: orderDetails,
    };
  }

  static mapGetOrderBySerial(order) {
    return {
      OrderEntrySystem: order.orderEntrySystem || '',
      IsPayed: order.isPayed || false,
      TotalPaymentReceived: order.totalPaymentReceived || 0,
      CreatedByBlueFirstName: order.orderedBy?.firstname || '',
      CreatedByBlueLastName: order.orderedBy?.lastname || '',
      CreatedByVoluFirstName: order.salesRep?.firstName || '',
      CreatedByVoluLastName: order.salesRep?.lastName || '',
      OrderSerials: order.orderSerials || '',
      invoiceableOn: order.invoiceableOn
        ? new Date(order.invoiceableOn)
        : undefined,
      OrderStatus: order.orderStatus || '',
      OrderType: order.orderType || '',
      ShippingMethodID: order.shippingMethodId || 0,
      //   PrivateNotes: order.privateNotes || '',
      Freight: order.totalShippingCost || 0,
      OldOrder: order.oldOrder || false,
      TaxShipping:
        (order.salesTaxRate1 || 0) +
        (order.salesTaxRate2 || 0) +
        (order.salesTaxRate3 || 0),
      notes: order.orderComments || '',
      IsCustomerNameShow: order.isCustomerNameShow || false,
      OrderID: order.id,
      CustomerID: order.customerId || 0,
      PaymentAmount: order.paymentAmount || 0,
      CustomerCompany: order.billingCompanyName || '',
      ShipCompanyName: order.shipCompanyName || '',
      ShipFirstName: order.shipFirstName || '',
      ShipLastName: order.shipLastName || '',
      CustomerFName: order.billingFirstName || '',
      CustomerLName: order.billingLastName || '',
      OrderDate: order.orderDate ? new Date(order.orderDate) : undefined,
      BillingStreetAddress1: order.billingAddress1 || '',
      BillingStreetAddress2: order.billingAddress2 || '',
      BillingCity1: order.billingCity || '',
      BillingCountry1: order.billingCountry || '',
      BillingState: order.billingState || '',
      BillingPhoneNumber: order.billingPhoneNumber || '',
      IsTaxExempt: order.orderTaxExempt || false,
      BillingPostalCode: order.billingPostalCode || '',
      ShipAddress1: order.shipAddress1 || '',
      ShipAddress2: order.shipAddress2 || '',
      ShipCity: order.shipCity || '',
      ShipCountry: order.shipCountry || '',
      ShipState: order.shipState || '',
      ShipPhoneNumber: order.shipPhoneNumber || '',
      ShipPostalCode: order.shipPostalCode || '',
      SalesTaxRate1:
        (order.salesTaxRate1 || 0) +
        (order.salesTaxRate2 || 0) +
        (order.salesTaxRate3 || 0),
      SalesTax1: order.salesTax1 || 0,
      IsCustomerEmailShow: order.isCustomerEmailShow || false,
      orderDetails: order.orderDetails.map((detail) => ({
        productId: detail.productId,
        Options: detail.options,
        QtyOnPackingSlip: detail.qtyOnPackingSlip,
        QtyShipped: detail.qtyShipped,
        QtyOnBackOrder: detail.qtyOnBackOrder,
        shippedQty: 0, // Computed below
        parent: detail.parent,
        parentName: detail.parentName,
        ProductSerials: detail.productSerials,
        isChild: detail.isChild,
        isCategoriesOption: detail.isCategoriesOption,
        ProductCode: detail.productCode,
        ProductName: detail.productName,
        description: detail.description,
        Qty: detail.quantity,
        Price: detail.productPrice,
        Discount: detail.discountValue,
      })),
    };
  }

  static mapGetTrackShipping(tracking, orders, matchedOrderDetail, notes) {
    return {
      ProductCode: tracking.productCode || '',
      isCategoriesOption: matchedOrderDetail?.isCategoriesOption || false,
      isChild: tracking.isChild || false,
      ProductName: matchedOrderDetail?.productName || '',
      OptionID: matchedOrderDetail?.optionId,
      IsCustomerNameShow: orders[0].isCustomerNameShow || false,
      OrderComments: orders[0].orderComments || '',
      notes: orders[0].orderComments || '',
      OrderNotes: orders[0].orderNotes || '',
      // PrivateNotes: orders[0].privateNotes || '',
      ShipEmailAddress: orders[0].shipEmailAddress || '',
      PONum: orders[0].poNum || '',
      TrackingNo: orders[0].trackingNo || '',
      CustomerID: orders[0].customerId,
      OrderID: orders[0].id,
      Incoterm: orders[0].incoterm || '',
      ModifiedByBlueFirstName: orders[0].modifiedBy?.firstname || '',
      ModifiedByBlueLastName: orders[0].modifiedBy?.lastname || '',
      CreatedByBlueFirstName: orders[0].orderedBy?.firstname || '',
      CreatedByBlueLastName: orders[0].orderedBy?.lastname || '',
      CreatedByVoluFirstName: orders[0].salesRep?.firstName || '',
      CreatedByVoluLastName: orders[0].salesRep?.lastName || '',
      OrderStatus: orders[0].orderStatus || '',
      OrderType: orders[0].orderType || '',
      ShippingMethodID: orders[0].shippingMethodId,
      PaymentAmount: orders[0].paymentAmount || 0,
      CustomerCompany: orders[0].billingCompanyName || '',
      ShipCompanyName: orders[0].shipCompanyName || '',
      ShipFirstName: orders[0].shipFirstName || '',
      ShipLastName: orders[0].shipLastName || '',
      CustomerFName: orders[0].billingFirstName || '',
      CustomerLName: orders[0].billingLastName || '',
      OrderDate: orders[0].orderDate
        ? new Date(orders[0].orderDate)
        : undefined,
      OrderDatePDF: orders[0].orderDate
        ? new Date(orders[0].orderDate).toISOString().split('T')[0]
        : '',
      BillingStreetAddress1: orders[0].billingAddress1 || '',
      BillingStreetAddress2: orders[0].billingAddress2 || '',
      BillingCity1: orders[0].billingCity || '',
      BillingCountry1: orders[0].billingCountry || '',
      BillingState: orders[0].billingState || '',
      BillingPhoneNumber: orders[0].billingPhoneNumber || '',
      BillingPostalCode: orders[0].billingPostalCode || '',
      ShipAddress1: orders[0].shipAddress1 || '',
      ShipAddress2: orders[0].shipAddress2 || '',
      ShipCity: orders[0].shipCity || '',
      ShipCountry: orders[0].shipCountry || '',
      ShipState: orders[0].shipState || '',
      ShipPhoneNumber: orders[0].shipPhoneNumber || '',
      ShipPostalCode: orders[0].shipPostalCode || '',
      gpn: matchedOrderDetail?.product?.gpn || '',
      SalesTaxRate1:
        (orders[0].salesTaxRate1 || 0) +
        (orders[0].salesTaxRate2 || 0) +
        (orders[0].salesTaxRate3 || 0),
      SalesTax1: orders[0].salesTax1,
      IsCustomerEmailShow: orders[0].isCustomerEmailShow || false,
      tagIds: orders[0].tagTable?.map((tt) => tt.tagId) || [],
      notesHistory: notes,
      id: tracking.id,
      trackShippingId: tracking.trackShippingId,
      ProductId: tracking.productId,
      QtyOnPackingSlip: tracking.quantity,
      createdAt: tracking.createdAt ? new Date(tracking.createdAt) : undefined,
    };
  }

  static mapGetOpenOrdersByProductId(order) {
    return {
      ProductCode: order.orderDetails[0]?.productCode || '',
      IsPayed: order.isPayed || false,
      OrderEntrySystem: order.orderEntrySystem || '',
      BillingAddress1: order.billingAddress1 || '',
      BillingAddress2: order.billingAddress2 || '',
      PONum: order.poNum || '',
      BillingCity: order.billingCity || '',
      BillingCompanyName: order.billingCompanyName || '',
      BillingCountry: order.billingCountry || '',
      BillingFaxNumber: order.billingFaxNumber || '',
      BillingFirstName: order.billingFirstName || '',
      BillingLastName: order.billingLastName || '',
      BillingPhoneNumber: order.billingPhoneNumber || '',
      BillingPostalCode: order.billingPostalCode || '',
      BillingState: order.billingState || '',
      OrderComments: order.orderComments || '',
      ShipAddress1: order.shipAddress1 || '',
      ShipAddress2: order.shipAddress2 || '',
      ShipCity: order.shipCity || '',
      ShipCompanyName: order.shipCompanyName || '',
      ShipCountry: order.shipCountry || '',
      ShipDate: order.shipDate ? new Date(order.shipDate) : undefined,
      ShipFaxNumber: order.shipFaxNumber || '',
      ShipFirstName: order.shipFirstName || '',
      ShipLastName: order.shipLastName || '',
      Shipped: order.shipped || false,
      ShipPhoneNumber: order.shipPhoneNumber || '',
      ShipPostalCode: order.shipPostalCode || '',
      ShipState: order.shipState || '',
      OrderNotes: order.orderNotes || '',
      CreatedByBlueFirstName: order.orderedBy?.firstname || '',
      CreatedByBlueLastName: order.orderedBy?.lastname || '',
      CreatedByVoluFirstName: order.salesRep?.firstName || '',
      CreatedByVoluLastName: order.salesRep?.lastName || '',
      OrderSerials: order.orderSerials || '',
      OrderID: order.id,
      QuoteNo: order.quote?.id || '',
      QuoteDate: order.quote?.quoteDate
        ? new Date(order.quote.quoteDate)
        : undefined,
      invoiceableOn: order.invoiceableOn
        ? new Date(order.invoiceableOn)
        : undefined,
      CustomerID: order.customerId?.toString(),
      OrderStatus: order.orderStatus || '',
      PaymentAmount: order.paymentAmount || 0,
      CompanyName: order.billingCompanyName || '',
      FirstName: order.billingFirstName || '',
      LastName: order.billingLastName || '',
      OrderDate: order.orderDate ? new Date(order.orderDate) : undefined,
      City: order.billingCity || '',
      EmailAddress: order.customer?.email || '',
      OldOrder: order.oldOrder || false,
    };
  }

  static mapGetOrderTrack(result){
     
   return {
     Id: result.id,
     TrackingNo: result.trackingNo,
     Gateway: result.gateway,
     ShipDate: result.shipDate,
     OrderId: result,
     ShipmentCost: 1,
     ShippingMethodID: 701,
     Package: null,
     Form: null,
     IsImported: 0,
     OrderType: 'Shipped',
     updatedBy: 160,
     id: 73909,
     trackShippingId: 33710,
     orderId: 70469,
     quantity: 1,
     productId: 200542,
     productCode: 'DB26-2-DB25-DB9-RJ45-CABLE',
     productDescription:
       '<p id=\\\\\\"details\\\\\\">Converts the HD-26F connector on DB26 #2 (Fire 3), neoVI FIRE2, and RAD-Gigastar to DB-25M, DB-9 and RJ-45 (Ethernet) connectors. Compatible with neoVI FIRE3 (2nd DB26), RAD-Gigastar, neoVI Fire 2, Fire 2 VNET.</p>\n',
     isChild: 1,
     displayOrder: 5,
     createdAt: '2025-08-27T12:29:15.000Z',
     createdBy: 160,
     updatedAt: '2025-08-27T12:29:15.000Z',
     countOfLineItems: '6',
   };
  }
}
