export class EndUserEntity{
   id:number;
   firstName:string;
   lastName:string;
   email:string;
   phoneNumber:string;
   billingAddress1:string;
   billingAddress2:string;
   city:string;
   state:string;
   postalCode:string;
   country:string;
   createdAt:Date;
   modifiedAt:Date;
   createdBy:number
   modifiedBy:number
   hide:boolean;
   external:boolean;
}