import { Product as PrismaProduct, Prisma } from '@prisma/client';
import { ProductEntity } from '../entities/product.entity';

export class ProductMapper {
  static toDomain(prismaProduct: PrismaProduct): ProductEntity {
    return {
      productId: prismaProduct.ProductID,
      productCode: prismaProduct.ProductCode ?? undefined,
      productName: prismaProduct.ProductName ?? undefined,
      productDescriptionShort: prismaProduct.ProductDescriptionShort ?? undefined,
      productDescription: prismaProduct.ProductDescription ?? undefined,
      productNameShort: prismaProduct.ProductNameShort ?? undefined,
      productPrice: prismaProduct.ProductPrice,
      productPriceYuan: prismaProduct.ProductPriceYuan,
      productPriceYen: prismaProduct.ProductPriceYen,
      productPriceEuro: prismaProduct.ProductPriceEuro,
      productPricePound: prismaProduct.ProductPricePound,
      productPriceWon: prismaProduct.ProductPriceWON,
      productPriceInr: prismaProduct.ProductPriceINR,
      productWeight: prismaProduct.ProductWeight ?? undefined,
      freeShippingItem: prismaProduct.FreeShippingItem ?? undefined,
      photoAltText: prismaProduct.Photo_AltText ?? undefined,
      hideFreeAccessories: prismaProduct.Hide_FreeAccessories ?? undefined,
      taxableProduct: prismaProduct.TaxableProduct ?? undefined,
      techSpecs: prismaProduct.TechSpecs ?? undefined,
      hideProduct: prismaProduct.HideProduct
        ? prismaProduct.HideProduct.toLowerCase() === 'true'
        : undefined, 
      modifyOn: prismaProduct.ModifyOn ?? undefined,
      createdOn: prismaProduct.CreatedOn ?? undefined,
      stockStatus: prismaProduct.StockStatus ?? undefined,
      availability: prismaProduct.Availability ?? undefined,
      productPriceName: prismaProduct.ProductPrice_Name ?? undefined,
      productManufacturer: prismaProduct.ProductManufacturer ?? undefined,
      salePriceName: prismaProduct.SalePrice_Name ?? undefined,
      accessories: prismaProduct.Accessories ?? undefined,
      optionIds: prismaProduct.OptionIDs ?? undefined,
      freeAccessories: prismaProduct.FreeAccessories ?? undefined,
      productDetailUrl: prismaProduct.ProductDetailURL ?? undefined,
      extInfo: prismaProduct.ExtInfo ?? undefined,
      productDescriptionAbovePricing: prismaProduct.ProductDescription_AbovePricing ?? undefined,
      productPhotoUrl: prismaProduct.ProductPhotoURL ?? undefined,
      discount: prismaProduct.Discount,
      metaTagDescription: prismaProduct.METATAG_Description ?? undefined,
      metaTagKeywords: prismaProduct.METATAG_Keywords ?? undefined,
      priorityIndex: prismaProduct.PriorityIndex,
      hideWhenOutOfStock: prismaProduct.HideWhenOutOfStock,
      isActive: prismaProduct.IsActive,
      isCompleted: prismaProduct.isCompleted ?? undefined,
      isDeleted: prismaProduct.IsDeleted,
      isFeatured: prismaProduct.IsFeatured,
      titleImage: prismaProduct.TitleImage ?? undefined,
      isSerialAble: prismaProduct.isSerialAble,
      isFreeProduct: prismaProduct.IsFreeProduct,
      harmonizedCode: prismaProduct.HarmonizedCode ?? undefined,
      exportControlClassificationNumber: prismaProduct.ExportControlClassificationNumber ?? undefined,
      unitOfMeasure: prismaProduct.UnitOfMeasure ?? undefined,
      countryOfOrigin: prismaProduct.CountryOfOrigin ?? undefined,
      exportDescription: prismaProduct.ExportDescription ?? undefined,
      groupId: prismaProduct.GroupId ?? undefined,
      backlogLeadtime: prismaProduct.backlog_leadtime ?? undefined,
      backlogComments: prismaProduct.backlog_comments ?? undefined,
      backlogPriority: prismaProduct.backlog_priority,
      backlogShow: prismaProduct.backlog_show,
      updatedDateBacklogComment: prismaProduct.updatedDateBacklogComment ?? undefined,
      holdForApproval: prismaProduct.holdForApproval,
      accessory: prismaProduct.Accessory,
      maintenance: prismaProduct.Maintenance,
      upgrade: prismaProduct.Upgrade,
      resale: prismaProduct.Resale,
      productClassId: prismaProduct.productClassId ?? undefined,
      productSubClassId: prismaProduct.productSubClassId ?? undefined,
      gpn: prismaProduct.gpn ?? undefined,
      storeCategory: prismaProduct.StoreCategory,
      isMultiClassification: prismaProduct.isMultiClassification ?? undefined,
      createdBy: prismaProduct.CreatedBy ?? undefined,
      modifiedBy: prismaProduct.ModifiedBy ?? undefined,
    };
  }

  static toPersistence(product: ProductEntity): Prisma.ProductCreateInput {
    return {
      ProductID: product.productId,
      ProductCode: product.productCode,
      ProductName: product.productName,
      ProductDescriptionShort: product.productDescriptionShort,
      ProductDescription: product.productDescription,
      ProductNameShort: product.productNameShort,
      ProductPrice: product.productPrice,
      ProductPriceYuan: product.productPriceYuan,
      ProductPriceYen: product.productPriceYen,
      ProductPriceEuro: product.productPriceEuro,
      ProductPricePound: product.productPricePound,
      ProductPriceWON: product.productPriceWon,
      ProductPriceINR: product.productPriceInr,
      ProductWeight: product.productWeight,
      FreeShippingItem: product.freeShippingItem,
      Photo_AltText: product.photoAltText,
      Hide_FreeAccessories: product.hideFreeAccessories,
      TaxableProduct: product.taxableProduct,
      TechSpecs: product.techSpecs,
      HideProduct: product.hideProduct !== undefined
        ? String(product.hideProduct)
        : undefined, 
      ModifyOn: product.modifyOn,
      CreatedOn: product.createdOn,
      StockStatus: product.stockStatus,
      Availability: product.availability,
      ProductPrice_Name: product.productPriceName,
      ProductManufacturer: product.productManufacturer,
      SalePrice_Name: product.salePriceName,
      Accessories: product.accessories,
      OptionIDs: product.optionIds,
      FreeAccessories: product.freeAccessories,
      ProductDetailURL: product.productDetailUrl,
      ExtInfo: product.extInfo,
      ProductDescription_AbovePricing: product.productDescriptionAbovePricing,
      ProductPhotoURL: product.productPhotoUrl,
      Discount: product.discount,
      METATAG_Description: product.metaTagDescription,
      METATAG_Keywords: product.metaTagKeywords,
      PriorityIndex: product.priorityIndex,
      HideWhenOutOfStock: product.hideWhenOutOfStock,
      IsActive: product.isActive,
      isCompleted: product.isCompleted,
      IsDeleted: product.isDeleted,
      IsFeatured: product.isFeatured,
      TitleImage: product.titleImage,
      isSerialAble: product.isSerialAble,
      IsFreeProduct: product.isFreeProduct,
      HarmonizedCode: product.harmonizedCode,
      ExportControlClassificationNumber: product.exportControlClassificationNumber,
      UnitOfMeasure: product.unitOfMeasure,
      CountryOfOrigin: product.countryOfOrigin,
      ExportDescription: product.exportDescription,
      GroupId: product.groupId,
      backlog_leadtime: product.backlogLeadtime,
      backlog_comments: product.backlogComments,
      backlog_priority: product.backlogPriority,
      backlog_show: product.backlogShow,
      updatedDateBacklogComment: product.updatedDateBacklogComment,
      holdForApproval: product.holdForApproval,
      Accessory: product.accessory,
      Maintenance: product.maintenance,
      Upgrade: product.upgrade,
      Resale: product.resale,
      productClass: product.productClassId
        ? { connect: { Id: product.productClassId } }
        : undefined,

      productSubClass: product.productSubClassId
        ? { connect: { Id: product.productSubClassId } }
        : undefined,
      gpn: product.gpn,
      StoreCategory: product.storeCategory,
      isMultiClassification: product.isMultiClassification,
      CreatedBy: product.createdBy,
      ModifiedBy: product.modifiedBy,
    };
  }

  static toSummary(raw: {
    ProductID: number;
    ProductCode: string | null;
    IsFeatured: boolean;
    HideProduct: string | null;
  }): ProductEntity {
    return {
      productId: raw.ProductID,
      productCode: raw.ProductCode ?? undefined,
      isFeatured: raw.IsFeatured,
      hideProduct: raw.HideProduct ?? undefined,
    } as ProductEntity;
  }
}
