-- AlterTable
ALTER TABLE `tag` ADD COLUMN `color` VARCHAR(191) NOT NULL DEFAULT 'white',
    ADD COLUMN `createdBy` VARCHAR(191) NOT NULL DEFAULT 'system',
    ADD COLUMN `typeId` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `updatedBy` VARCHAR(191) NOT NULL DEFAULT 'system';
